//*
// Licensed to the Apache Software Foundation (ASF) under one
// or more contributor license agreements.  See the NOTICE file
// distributed with this work for additional information
// regarding copyright ownership.  The ASF licenses this file
// to you under the Apache License, Version 2.0 (the
// "License"); you may not use this file except in compliance
// with the License.  You may obtain a copy of the License at
//
//     http://www.apache.org/licenses/LICENSE-2.0
//
// Unless required by applicable law or agreed to in writing, software
// distributed under the License is distributed on an "AS IS" BASIS,
// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
// See the License for the specific language governing permissions and
// limitations under the License.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.23.0
// 	protoc        v3.15.4
// source: Snapshot.proto

package pb

import (
	proto "github.com/golang/protobuf/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// This is a compile-time assertion that a sufficiently up-to-date version
// of the legacy proto package is being used.
const _ = proto.ProtoPackageIsVersion4

type SnapshotDescription_Type int32

const (
	SnapshotDescription_DISABLED  SnapshotDescription_Type = 0
	SnapshotDescription_FLUSH     SnapshotDescription_Type = 1
	SnapshotDescription_SKIPFLUSH SnapshotDescription_Type = 2
)

// Enum value maps for SnapshotDescription_Type.
var (
	SnapshotDescription_Type_name = map[int32]string{
		0: "DISABLED",
		1: "FLUSH",
		2: "SKIPFLUSH",
	}
	SnapshotDescription_Type_value = map[string]int32{
		"DISABLED":  0,
		"FLUSH":     1,
		"SKIPFLUSH": 2,
	}
)

func (x SnapshotDescription_Type) Enum() *SnapshotDescription_Type {
	p := new(SnapshotDescription_Type)
	*p = x
	return p
}

func (x SnapshotDescription_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SnapshotDescription_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_Snapshot_proto_enumTypes[0].Descriptor()
}

func (SnapshotDescription_Type) Type() protoreflect.EnumType {
	return &file_Snapshot_proto_enumTypes[0]
}

func (x SnapshotDescription_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Do not use.
func (x *SnapshotDescription_Type) UnmarshalJSON(b []byte) error {
	num, err := protoimpl.X.UnmarshalJSONEnum(x.Descriptor(), b)
	if err != nil {
		return err
	}
	*x = SnapshotDescription_Type(num)
	return nil
}

// Deprecated: Use SnapshotDescription_Type.Descriptor instead.
func (SnapshotDescription_Type) EnumDescriptor() ([]byte, []int) {
	return file_Snapshot_proto_rawDescGZIP(), []int{0, 0}
}

//*
// Description of the snapshot to take
type SnapshotDescription struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name         *string                   `protobuf:"bytes,1,req,name=name" json:"name,omitempty"`
	Table        *string                   `protobuf:"bytes,2,opt,name=table" json:"table,omitempty"` // not needed for delete, but checked for in taking snapshot
	CreationTime *int64                    `protobuf:"varint,3,opt,name=creation_time,json=creationTime,def=0" json:"creation_time,omitempty"`
	Type         *SnapshotDescription_Type `protobuf:"varint,4,opt,name=type,enum=pb.SnapshotDescription_Type,def=1" json:"type,omitempty"`
	Version      *int32                    `protobuf:"varint,5,opt,name=version" json:"version,omitempty"`
	Owner        *string                   `protobuf:"bytes,6,opt,name=owner" json:"owner,omitempty"`
	Ttl          *int64                    `protobuf:"varint,8,opt,name=ttl,def=0" json:"ttl,omitempty"`
}

// Default values for SnapshotDescription fields.
const (
	Default_SnapshotDescription_CreationTime = int64(0)
	Default_SnapshotDescription_Type         = SnapshotDescription_FLUSH
	Default_SnapshotDescription_Ttl          = int64(0)
)

func (x *SnapshotDescription) Reset() {
	*x = SnapshotDescription{}
	if protoimpl.UnsafeEnabled {
		mi := &file_Snapshot_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *SnapshotDescription) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SnapshotDescription) ProtoMessage() {}

func (x *SnapshotDescription) ProtoReflect() protoreflect.Message {
	mi := &file_Snapshot_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SnapshotDescription.ProtoReflect.Descriptor instead.
func (*SnapshotDescription) Descriptor() ([]byte, []int) {
	return file_Snapshot_proto_rawDescGZIP(), []int{0}
}

func (x *SnapshotDescription) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *SnapshotDescription) GetTable() string {
	if x != nil && x.Table != nil {
		return *x.Table
	}
	return ""
}

func (x *SnapshotDescription) GetCreationTime() int64 {
	if x != nil && x.CreationTime != nil {
		return *x.CreationTime
	}
	return Default_SnapshotDescription_CreationTime
}

func (x *SnapshotDescription) GetType() SnapshotDescription_Type {
	if x != nil && x.Type != nil {
		return *x.Type
	}
	return Default_SnapshotDescription_Type
}

func (x *SnapshotDescription) GetVersion() int32 {
	if x != nil && x.Version != nil {
		return *x.Version
	}
	return 0
}

func (x *SnapshotDescription) GetOwner() string {
	if x != nil && x.Owner != nil {
		return *x.Owner
	}
	return ""
}

func (x *SnapshotDescription) GetTtl() int64 {
	if x != nil && x.Ttl != nil {
		return *x.Ttl
	}
	return Default_SnapshotDescription_Ttl
}

var File_Snapshot_proto protoreflect.FileDescriptor

var file_Snapshot_proto_rawDesc = []byte{
	0x0a, 0x0e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f,
	0x12, 0x02, 0x70, 0x62, 0x22, 0x95, 0x02, 0x0a, 0x13, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f,
	0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x12, 0x0a, 0x04,
	0x6e, 0x61, 0x6d, 0x65, 0x18, 0x01, 0x20, 0x02, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65,
	0x12, 0x14, 0x0a, 0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52,
	0x05, 0x74, 0x61, 0x62, 0x6c, 0x65, 0x12, 0x26, 0x0a, 0x0d, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69,
	0x6f, 0x6e, 0x5f, 0x74, 0x69, 0x6d, 0x65, 0x18, 0x03, 0x20, 0x01, 0x28, 0x03, 0x3a, 0x01, 0x30,
	0x52, 0x0c, 0x63, 0x72, 0x65, 0x61, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x69, 0x6d, 0x65, 0x12, 0x37,
	0x0a, 0x04, 0x74, 0x79, 0x70, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0e, 0x32, 0x1c, 0x2e, 0x70,
	0x62, 0x2e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x44, 0x65, 0x73, 0x63, 0x72, 0x69,
	0x70, 0x74, 0x69, 0x6f, 0x6e, 0x2e, 0x54, 0x79, 0x70, 0x65, 0x3a, 0x05, 0x46, 0x4c, 0x55, 0x53,
	0x48, 0x52, 0x04, 0x74, 0x79, 0x70, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69,
	0x6f, 0x6e, 0x18, 0x05, 0x20, 0x01, 0x28, 0x05, 0x52, 0x07, 0x76, 0x65, 0x72, 0x73, 0x69, 0x6f,
	0x6e, 0x12, 0x14, 0x0a, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x18, 0x06, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x05, 0x6f, 0x77, 0x6e, 0x65, 0x72, 0x12, 0x13, 0x0a, 0x03, 0x74, 0x74, 0x6c, 0x18, 0x08,
	0x20, 0x01, 0x28, 0x03, 0x3a, 0x01, 0x30, 0x52, 0x03, 0x74, 0x74, 0x6c, 0x22, 0x2e, 0x0a, 0x04,
	0x54, 0x79, 0x70, 0x65, 0x12, 0x0c, 0x0a, 0x08, 0x44, 0x49, 0x53, 0x41, 0x42, 0x4c, 0x45, 0x44,
	0x10, 0x00, 0x12, 0x09, 0x0a, 0x05, 0x46, 0x4c, 0x55, 0x53, 0x48, 0x10, 0x01, 0x12, 0x0d, 0x0a,
	0x09, 0x53, 0x4b, 0x49, 0x50, 0x46, 0x4c, 0x55, 0x53, 0x48, 0x10, 0x02, 0x42, 0x4b, 0x0a, 0x31,
	0x6f, 0x72, 0x67, 0x2e, 0x61, 0x70, 0x61, 0x63, 0x68, 0x65, 0x2e, 0x68, 0x61, 0x64, 0x6f, 0x6f,
	0x70, 0x2e, 0x68, 0x62, 0x61, 0x73, 0x65, 0x2e, 0x73, 0x68, 0x61, 0x64, 0x65, 0x64, 0x2e, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2e, 0x67, 0x65, 0x6e, 0x65, 0x72, 0x61, 0x74, 0x65,
	0x64, 0x42, 0x0e, 0x53, 0x6e, 0x61, 0x70, 0x73, 0x68, 0x6f, 0x74, 0x50, 0x72, 0x6f, 0x74, 0x6f,
	0x73, 0x48, 0x01, 0x88, 0x01, 0x01, 0xa0, 0x01, 0x01,
}

var (
	file_Snapshot_proto_rawDescOnce sync.Once
	file_Snapshot_proto_rawDescData = file_Snapshot_proto_rawDesc
)

func file_Snapshot_proto_rawDescGZIP() []byte {
	file_Snapshot_proto_rawDescOnce.Do(func() {
		file_Snapshot_proto_rawDescData = protoimpl.X.CompressGZIP(file_Snapshot_proto_rawDescData)
	})
	return file_Snapshot_proto_rawDescData
}

var file_Snapshot_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_Snapshot_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_Snapshot_proto_goTypes = []interface{}{
	(SnapshotDescription_Type)(0), // 0: pb.SnapshotDescription.Type
	(*SnapshotDescription)(nil),   // 1: pb.SnapshotDescription
}
var file_Snapshot_proto_depIdxs = []int32{
	0, // 0: pb.SnapshotDescription.type:type_name -> pb.SnapshotDescription.Type
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_Snapshot_proto_init() }
func file_Snapshot_proto_init() {
	if File_Snapshot_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_Snapshot_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*SnapshotDescription); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_Snapshot_proto_rawDesc,
			NumEnums:      1,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_Snapshot_proto_goTypes,
		DependencyIndexes: file_Snapshot_proto_depIdxs,
		EnumInfos:         file_Snapshot_proto_enumTypes,
		MessageInfos:      file_Snapshot_proto_msgTypes,
	}.Build()
	File_Snapshot_proto = out.File
	file_Snapshot_proto_rawDesc = nil
	file_Snapshot_proto_goTypes = nil
	file_Snapshot_proto_depIdxs = nil
}
